#!/usr/bin/env bash

# shellcheck disable=SC1090  # ROS_DISTRO is set at build time
source /opt/ros/${ROS_DISTRO}/setup.bash
# shellcheck disable=SC1091  # generated by colcon build
source /ros_ws/install/local_setup.sh

exec "${@}"
