name: Main CI/CD

on:
  push:
    branches: [main, master]
    tags:
      - 'v*'
  pull_request:
  workflow_dispatch:

jobs:
  call-docker-build:
    uses: ycpss91255-docker/template/.github/workflows/build-worker.yaml@v0.12.3
    with:
      image_name: urg_node_humble
      build_runtime: false

  call-release:
    needs: call-docker-build
    if: startsWith(github.ref, 'refs/tags/')
    uses: ycpss91255-docker/template/.github/workflows/release-worker.yaml@v0.12.3
    with:
      archive_name_prefix: urg_node_humble
